### ISSUE TITLE
Use of uninitialized value $type in hash element at /usr/bin/kbt line 155

### ISSUE THREAD

**Issue by tokarthik** [llavaud/kbt#5]
Use of uninitialized value $type in hash element at /usr/bin/kbt line 155
while exporting into file

**Comment by llavaud** [comment]
What command line did you used to export ?

**Comment by karthikgreentrend** [comment]
thanks for your reply 
export all resources in a local file
kbt export --file todaybkup

**Comment by karthikgreentrend** [comment]
[
<img width="634" alt="Screen Shot 2019-03-25 at 6 06 35 AM" src="https://user-images.githubusercontent.com/14162959/54898442-433ae300-4ec4-11e9-9f54-9d21892b1838.png">
](url)

**Comment by karthikgreentrend** [comment]
please let me know if you need any more details

**Comment by karthikgreentrend** [comment]
<img width="704" alt="Screen Shot 2019-03-25 at 6 10 19 AM" src="https://user-images.githubusercontent.com/14162959/54898569-b7758680-4ec4-11e9-8321-72adaee7eabc.png">

**Comment by karthikgreentrend** [comment]
able to view the ess connected using kbt list

**Comment by llavaud** [comment]
> please let me know if you need any more details

which elasticsearch version ?

**Comment by karthikgreentrend** [comment]
@llavaud please let me know if you need more details

**Comment by karthikgreentrend** [comment]
> > please let me know if you need any more details
> 
> which elasticsearch version ?

6.6.1
